CREATE TABLE parent_account.goal
(
    goal_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    child_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT goal_pk
        PRIMARY KEY (goal_id),
    CONSTRAINT goal_child_id__fk
        FOREIGN KEY (child_id) REFERENCES parent_account.child (child_id),
    CONSTRAINT goal_subject_id__fk
        FOREIGN KEY (subject_id) REFERENCES tutor_profile.subject (subject_id)
);

CREATE TABLE session.progress
(
    progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    goal_id BIGINT NOT NULL,
    percentage_complete INTEGER NOT NULL,
    session_id BIGINT NOT NULL,
    CONSTRAINT progress_pk
        PRIMARY KEY (progress_id),
    CONSTRAINT progress_goal_id__fk
        FOREIGN KEY (goal_id) REFERENCES parent_account.goal (goal_id),
    CONSTRAINT progress_session_id__fk
        FOREIGN KEY (session_id) REFERENCES session.session (session_id),
    CONSTRAINT progress_percentage_check
        CHECK (percentage_complete >= 0 AND percentage_complete <= 100)
);