CREATE SCHEMA IF NOT EXISTS tutor_profile;


create table tutor_profile.tutor
(
    tutor_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url              VARCHAR(255) not null,
    name             VARCHAR(50) not null,
    summary          VARCHAR(200) not null,
    min_grade_level  INTEGER not null,
    max_grade_level  INTEGER not null,
    constraint tutor_pk
        primary key (tutor_id)

);

create table tutor_profile.subject
(
    subject_id   INTEGER not null,
    subject_name VARCHAR(50) not null,
    constraint subject_pk
        primary key (subject_id)
);


create table tutor_profile.tutor_subject
(
    tutor_subject_id INTEGER not null,
    tutor_id         INTEGER not null,
    subject_id       INTEGER not null,
    constraint tutor_subject_pk
        primary key (tutor_subject_id),
    constraint subject_id__fk
        foreign key (subject_id) references TUTOR_PROFILE.SUBJECT (subject_id),
    constraint tutor_id__fk
        foreign key (tutor_id) references TUTOR_PROFILE.TUTOR (tutor_id)
);
-- ##############  Code Review table here  #################









-- ##############################################################

CREATE SCHEMA IF NOT EXISTS session;

-- ##############  Code for session, time slot, and tutor timeslot table here  #################





-- ##############################################################



CREATE SCHEMA IF NOT EXISTS parent_account;

-- ##############  Code for parent and child table here  #################









-- ##############################################################